sample_timeout: 6
debug: True
api_url: '$TESTING_API_URL'
access_token: '$TESTING_ACCESS_TOKEN'
substitutions:
  '{version}': 'v1'
  '<ACCESS_TOKEN>': '$TESTING_ACCESS_TOKEN'
  'api-sandbox.oftrust.net': '$TESTING_API_URL'
resp_attr_replacements:
  'product-api/products/{version}':
    - 'productCode': 'product_code'
  'message-api/messages/{version}':
    - '@id': 'id'
  'calendar-api/calendars/{version}':
    - '@id': 'id'
  'identity-api/identities/v1':
    - '@id': 'id'
    - '@id': 'from_identity'
  'identity-api/identities/v1/{from_identity}/link/{to_identity}':
    - '@type': 'type'
before_sample:
  'message-api/messages/{version}':
    resource: 'Identity'
    method: 'POST'
    subs:
      '@id': '<to identity ID>'
  'calendar-api/calendars/{version}':
    resource: 'Identity'
    method: 'POST'
    subs:
      '@id': '<to identity ID>'
  'identity-api/identities/v1/{from_identity}/link/{to_identity}':
    resource: 'Identity'
    method: 'POST'
    subs:
      '@id': 'to_identity'
  'product-api/products/{version}':
    resource: 'DeleteProduct'
    method: 'POST'
    subs: {}