sample_timeout: 5
debug: True
substitutions:
  '{version}': 'v1'
  '<ACCESS_TOKEN>': '$ACCESS_TOKEN'
  'api-sandbox.oftrust.net': '$TESTING_API_URL'
resp_attr_replacements:
  '/products/{version}':
    'productCode': 'product_code'
  '/messages/{version}':
    '@id': 'id'
